name: Build OPNsense image for RPI

on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    name: Build OPNsense image for RPI4 Model B
    runs-on: ["self-hosted", "freebsd", "arm64", "14.2"]

    steps:
      - name: Checkout build source
        uses: actions/checkout@v4

      - name: Copy build tools to /usr
        run: |
          cd /usr/
          cp -r $GITHUB_WORKSPACE /usr/tools

      - name: Update build tools
        run: |
          cd /usr/tools/
          make update

      - name: Build base
        run: |
          cd /usr/tools/
          make base DEVICE=RPI
          
